import Chart from "chart.js";

const names = [
    'John Aby',
    'Abi Lori',
    'Abie Mila',
    'Laurie Sia',
    'Flowa Tulip',
    'Binuri Autumn',
    'Riley Oloy',
    'Miya Saly',
    'Binuri Fleury',
    'Nira Toura',
    'Pooya Firhan',
    'Stephanie Leeyam',
    'Youra George',
    'Hassan Ali',
    'Kenta Leeyam',
    'Marie Faily',
    'Darren Shinay',
    'Akeel Ali',
    'David Hererra',
    'Darren Shinay',
    'David Hererra',
    'David Hererra',
    'Hassan Ali',
    'George Jared',
    'Kenta Leeyam',
    'David Hererra',
    'Darren Shinay',
    'David Hererra',
    'Youra George',
    'George Jared',
    'Marie Faily',
    'David Hererra',
    'Darren Shinay',
    'Sandrine Loreiller',
    'Sandrine Loreiller',
    'Kenta Leeyam',
    'Sandrine Loreiller',
    'Darren Shinay',
    'Sandrine Loreiller',
    'Sandrine Loreiller',
    'Darren Shinay',
    'Sandrine Loreiller',
    'Sandrine Loreiller',
    'Hassan Ali',
    'George Jared',
    'Darren Shinay',
    'George Jared',
    'Marie Faily',
    'Marc Palaci',
    'Marc Palaci',
    'Kenta Leeyam',
    'Marc Palaci',
    'Marc Palaci',
    'Marie Faily',
    'Marc Palaci',
    'Marc Palaci',
    'Youra George',
    'Marc Palaci',
    'Marie Faily',
    'Hassan Ali',
    'George Jared',
    'Darren Shinay',
    'Akeel Ali',
    'Marc Palaci',
    'Marc Palaci',
    'Youra George',
    'Akeel Ali',
    'Akeel Ali',
    'Darren Shinay',
    'Akeel Ali',
    'Marie Faily',
    'Akeel Ali'
];

const thumbnails = [
    'https://randomuser.me/api/portraits/men/15.jpg',
    'https://randomuser.me/api/portraits/women/55.jpg',
    'https://randomuser.me/api/portraits/women/78.jpg',
    'https://randomuser.me/api/portraits/women/27.jpg',
    'https://randomuser.me/api/portraits/women/75.jpg',
    'https://randomuser.me/api/portraits/women/46.jpg',
    'https://randomuser.me/api/portraits/women/1.jpg',
    'https://randomuser.me/api/portraits/women/7.jpg',
    'https://randomuser.me/api/portraits/women/24.jpg',
    'https://randomuser.me/api/portraits/women/10.jpg',
    'https://randomuser.me/api/portraits/women/28.jpg',
    'https://randomuser.me/api/portraits/women/92.jpg',
    'https://randomuser.me/api/portraits/women/81.jpg',
    'https://randomuser.me/api/portraits/women/93.jpg',
    'https://randomuser.me/api/portraits/women/74.jpg',
    'https://randomuser.me/api/portraits/women/90.jpg',
    'https://randomuser.me/api/portraits/women/77.jpg',
    'https://randomuser.me/api/portraits/women/49.jpg',
    'https://randomuser.me/api/portraits/women/16.jpg',
    'https://randomuser.me/api/portraits/women/22.jpg',
    'https://randomuser.me/api/portraits/women/86.jpg',
    'https://randomuser.me/api/portraits/women/43.jpg',
    'https://randomuser.me/api/portraits/women/56.jpg',
    'https://randomuser.me/api/portraits/women/58.jpg',
    'https://randomuser.me/api/portraits/women/69.jpg',
    'https://randomuser.me/api/portraits/women/17.jpg',
    'https://randomuser.me/api/portraits/women/41.jpg',
    'https://randomuser.me/api/portraits/women/80.jpg',
    'https://randomuser.me/api/portraits/women/94.jpg',
    'https://randomuser.me/api/portraits/women/31.jpg',
    'https://randomuser.me/api/portraits/women/15.jpg',
    'https://randomuser.me/api/portraits/women/50.jpg',
    'https://randomuser.me/api/portraits/women/72.jpg',
    'https://randomuser.me/api/portraits/women/66.jpg',
    'https://randomuser.me/api/portraits/women/61.jpg',
    'https://randomuser.me/api/portraits/women/87.jpg',
    'https://randomuser.me/api/portraits/women/52.jpg',
    'https://randomuser.me/api/portraits/women/39.jpg',
    'https://randomuser.me/api/portraits/women/65.jpg',
    'https://randomuser.me/api/portraits/women/83.jpg',
    'https://randomuser.me/api/portraits/women/62.jpg',
    'https://randomuser.me/api/portraits/women/89.jpg',
    'https://randomuser.me/api/portraits/women/29.jpg',
    'https://randomuser.me/api/portraits/women/54.jpg',
    'https://randomuser.me/api/portraits/women/23.jpg',
    'https://randomuser.me/api/portraits/women/13.jpg',
    'https://randomuser.me/api/portraits/women/45.jpg',
    'https://randomuser.me/api/portraits/women/57.jpg',
    'https://randomuser.me/api/portraits/women/12.jpg',
    'https://randomuser.me/api/portraits/women/0.jpg',
    'https://randomuser.me/api/portraits/women/34.jpg',
    'https://randomuser.me/api/portraits/women/2.jpg',
    'https://randomuser.me/api/portraits/women/3.jpg',
    'https://randomuser.me/api/portraits/men/43.jpg',
    'https://randomuser.me/api/portraits/men/69.jpg',
    'https://randomuser.me/api/portraits/men/89.jpg',
    'https://randomuser.me/api/portraits/men/17.jpg',
    'https://randomuser.me/api/portraits/men/70.jpg',
    'https://randomuser.me/api/portraits/men/25.jpg',
    'https://randomuser.me/api/portraits/men/47.jpg',
    'https://randomuser.me/api/portraits/men/21.jpg',
    'https://randomuser.me/api/portraits/men/75.jpg',
    'https://randomuser.me/api/portraits/men/66.jpg',
    'https://randomuser.me/api/portraits/men/13.jpg',
    'https://randomuser.me/api/portraits/men/86.jpg',
    'https://randomuser.me/api/portraits/men/35.jpg',
    'https://randomuser.me/api/portraits/men/51.jpg',
    'https://randomuser.me/api/portraits/lego/1.jpg',
    'https://randomuser.me/api/portraits/lego/3.jpg',
    'https://randomuser.me/api/portraits/lego/7.jpg',
    'https://randomuser.me/api/portraits/lego/8.jpg',
    'https://randomuser.me/api/portraits/lego/6.jpg'
];

const users = _.map(thumbnails, (thumbnail, i) => {
    return {thumbnail, name: names[i]}
});

Template.classroom.viewmodel({
    users: users,
    onRendered: function () {
        _.each($(".progressChart"), element => {
            const power = parseInt(Math.random() * 100);
            const progressChart = new Chart(
                element,
                {
                    type: 'pie',
                    data: {
                        labels: ["Progress", "To do"],
                        datasets: [
                            {
                                label: "Percentage",
                                data: [power, 100 - power],
                                backgroundColor: ["#6FE0B8"],
                                hoverBackgroundColor: ["#50C692"]
                            }
                        ]
                    },

                }
            )
        })

    },
    createAssessment() {
        FlowRouter.go("/worksheet/trigonometry");
    }
})
